disabled_rules: # rule identifiers to exclude from running
opt_in_rules: # some rules are only opt-in
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_enum_raw_value
  - explicit_init
  - fatal_error_message
  - first_where
  - for_where
  - implicit_return
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - object_literal
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
included: # paths to include during linting. `--path` is ignored if present.
  - Cinema

force_cast: warning
type_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length:
    warning: 3
    error: 1
  excluded:
    - id
