disabled_rules: # rule identifiers to exclude from running
opt_in_rules: # some rules are only opt-in
included: # paths to include during linting. `--path` is ignored if present.
  - Cinema

force_cast: warning
type_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length:
    warning: 2
    error: 1
