disabled_rules:
  - fallthrough
  - switch_case_alignment
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - for_where
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - let_var_whitespace
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
included: # paths to include during linting. `--path` is ignored if present.
  - Cinema

force_cast: warning
type_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length:
    warning: 3
    error: 1
  excluded:
    - id
indentation: 2
nesting:
  type_level: 2
