// swiftlint:disable type_body_length
class SampleLibrary: MediaLibrary {

  // swiftlint:disable line_length
  private let data: [MediaItem] = [
    MediaItem(id: 14161, title: "2012", subtitle: "Das Ende der Welt", runtime: 151, year: 2009, diskType: .dvd),
    MediaItem(id: 7518, title: "Ab durch die Hecke", subtitle: nil, runtime: 89, year: 2006, diskType: .dvd),
    MediaItem(id: 812, title: "Aladdin", subtitle: nil, runtime: 86, year: 1992, diskType: .dvd),
    MediaItem(id: 11238, title: "Aladdin", subtitle: "Der König der Diebe", runtime: 78, year: 1996, diskType: .dvd),
    MediaItem(id: 15969, title: "Aladdin", subtitle: "Dschafars Rückkehr", runtime: 66, year: 1994, diskType: .dvd),
    MediaItem(id: 150540, title: "Alles steht Kopf", subtitle: nil, runtime: 95, year: 2015, diskType: .bluRay),
    MediaItem(id: 102899, title: "Ant-Man", subtitle: nil, runtime: 117, year: 2015, diskType: .bluRay),
    MediaItem(id: 9036, title: "Antarctica", subtitle: "Gefangen im Eis", runtime: 115, year: 2006, diskType: .dvd),
    MediaItem(id: 105864, title: "Arlo & Spot", subtitle: nil, runtime: 94, year: 2015, diskType: .bluRay),
    MediaItem(id: 9992, title: "Arthur und die Minimoys", subtitle: nil, runtime: 104, year: 2006, diskType: .bluRay),
    MediaItem(id: 26505, title: "Arthur und die Minimoys 2", subtitle: "Die Rückkehr des bösen M", runtime: 94, year: 2009, diskType: .bluRay),
    MediaItem(id: 42949, title: "Arthur und die Minimoys 3", subtitle: "Die große Entscheidung", runtime: 101, year: 2010, diskType: .bluRay),
    MediaItem(id: 10865, title: "Atlantis", subtitle: "Das Geheimnis der verlorenen Stadt", runtime: 96, year: 2001, diskType: .bluRay),
    MediaItem(id: 19995, title: "Avatar", subtitle: "Aufbruch nach Pandora", runtime: 162, year: 2009, diskType: .bluRay),
    MediaItem(id: 272, title: "Batman Begins", subtitle: nil, runtime: 140, year: 2005, diskType: .bluRay),
    MediaItem(id: 44833, title: "Battleship", subtitle: nil, runtime: 131, year: 2012, diskType: .bluRay),
    MediaItem(id: 177572, title: "BayMax", subtitle: "Riesiges Robowabohu", runtime: 102, year: 2014, diskType: .bluRay),
    MediaItem(id: 13053, title: "Bolt", subtitle: "Ein Hund für alle Fälle", runtime: 92, year: 2008, diskType: .dvd),
    MediaItem(id: 50619, title: "The Twilight Saga", subtitle: "Breaking Dawn - Teil 1", runtime: 117, year: 2011, diskType: .bluRay),
    MediaItem(id: 50620, title: "The Twilight Saga", subtitle: "Breaking Dawn - Teil 2", runtime: 115, year: 2012, diskType: .bluRay),
    MediaItem(id: 271110, title: "Captain America", subtitle: "Civil War", runtime: 148, year: 2016, diskType: .bluRay),
    MediaItem(id: 1771, title: "Captain America", subtitle: "The First Avenger", runtime: 124, year: 2011, diskType: .bluRay),
    MediaItem(id: 100402, title: "Captain America", subtitle: "The Return Of The First Avenger", runtime: 136, year: 2014, diskType: .bluRay),
    MediaItem(id: 920, title: "Cars", subtitle: nil, runtime: 112, year: 2006, diskType: .dvd),
    MediaItem(id: 49013, title: "Cars 2", subtitle: nil, runtime: 106, year: 2011, diskType: .bluRay),
    MediaItem(id: 9671, title: "Crocodile Dundee", subtitle: "Ein Krokodil zum Küssen", runtime: 94, year: 1986, diskType: .dvd),
    MediaItem(id: 9396, title: "Crocodile Dundee 2", subtitle: nil, runtime: 107, year: 1988, diskType: .dvd),
    MediaItem(id: 9487, title: "Das große Krabbeln", subtitle: nil, runtime: 95, year: 1998, diskType: .bluRay),
    MediaItem(id: 2059, title: "Das Vermächtnis der Tempelritter", subtitle: nil, runtime: 131, year: 2004, diskType: .bluRay),
    MediaItem(id: 6637, title: "Das Vermächtnis des geheimen Buches", subtitle: nil, runtime: 125, year: 2007, diskType: .bluRay),
    MediaItem(id: 122917, title: "Der Hobbit", subtitle: "Die Schlacht der fünf Heere", runtime: 144, year: 2014, diskType: .bluRay),
    MediaItem(id: 49051, title: "Der Hobbit", subtitle: "Eine unerwartete Reise", runtime: 169, year: 2012, diskType: .bluRay),
    MediaItem(id: 57158, title: "Der Hobbit", subtitle: "Smaugs Einöde", runtime: 161, year: 2013, diskType: .bluRay),
    MediaItem(id: 317180, title: "Der Maulwurf und seine Abenteuer als Fotograf", subtitle: nil, runtime: 44, year: 2000, diskType: .dvd),
    MediaItem(id: 317181, title: "Der Maulwurf und seine Abenteuer als Gärtner", subtitle: nil, runtime: 44, year: 2000, diskType: .dvd),
    MediaItem(id: 9016, title: "Der Schatzplanet", subtitle: nil, runtime: 96, year: 2002, diskType: .bluRay),
    MediaItem(id: 8366, title: "Der Schuh des Manitu", subtitle: nil, runtime: 88, year: 2001, diskType: .dvd),
    MediaItem(id: 1724, title: "Der unglaubliche Hulk", subtitle: nil, runtime: 112, year: 2008, diskType: .bluRay),
    MediaItem(id: 49519, title: "Die Croods", subtitle: nil, runtime: 99, year: 2013, diskType: .bluRay),
    MediaItem(id: 109445, title: "Die Eiskönigin", subtitle: "Völlig unverfroren", runtime: 102, year: 2013, diskType: .bluRay),
    MediaItem(id: 1635, title: "Die Insel", subtitle: nil, runtime: 136, year: 2005, diskType: .bluRay),
    MediaItem(id: 13836, title: "Die Jagd zum magischen Berg", subtitle: nil, runtime: 94, year: 2009, diskType: .dvd),
    MediaItem(id: 8698, title: "Die Liga der außergewöhnlichen Gentlemen", subtitle: nil, runtime: 105, year: 2003, diskType: .dvd),
    MediaItem(id: 585, title: "Die Monster AG", subtitle: nil, runtime: 92, year: 2001, diskType: .dvd),
    MediaItem(id: 62211, title: "Die Monster Uni", subtitle: nil, runtime: 104, year: 2013, diskType: .bluRay),
    MediaItem(id: 10020, title: "Die Schöne und das Biest", subtitle: nil, runtime: 87, year: 1991, diskType: .dvd),
    MediaItem(id: 35, title: "Die Simpsons", subtitle: "Der Film", runtime: 87, year: 2007, diskType: .bluRay),
    MediaItem(id: 9806, title: "Die Unglaublichen", subtitle: nil, runtime: 111, year: 2004, diskType: .dvd),
    MediaItem(id: 571, title: "Die Vögel", subtitle: nil, runtime: 115, year: 1963, diskType: .dvd),
    MediaItem(id: 284052, title: "Doctor Strange", subtitle: nil, runtime: 115, year: 2016, diskType: .bluRay),
    MediaItem(id: 10191, title: "Drachenzähmen leicht gemacht", subtitle: nil, runtime: 94, year: 2010, diskType: .dvd),
    MediaItem(id: 82702, title: "Drachenzähmen leicht gemacht 2", subtitle: nil, runtime: 102, year: 2014, diskType: .bluRay),
    MediaItem(id: 59803, title: "Das Dschungelbuch", subtitle: "Die Abenteuer des Mowgli", runtime: 76, year: 1973, diskType: .dvd),
    MediaItem(id: 14873, title: "Das Dschungelbuch 2", subtitle: nil, runtime: 69, year: 2003, diskType: .dvd),
    MediaItem(id: 27022, title: "Duell der Magier", subtitle: nil, runtime: 105, year: 2010, diskType: .dvd),
    MediaItem(id: 7551, title: "Déjà Vu", subtitle: "Wettlauf gegen die Zeit", runtime: 126, year: 2006, diskType: .bluRay),
    MediaItem(id: 24021, title: "The Twilight Saga", subtitle: "Eclipse", runtime: 124, year: 2010, diskType: .bluRay),
    MediaItem(id: 116711, title: "Epic", subtitle: "Verborgenes Königreich", runtime: 102, year: 2013, diskType: .bluRay),
    MediaItem(id: 2486, title: "Eragon", subtitle: "Das Vermächtnis der Drachenreiter", runtime: 100, year: 2006, diskType: .dvd),
    MediaItem(id: 9738, title: "Fantastic Four", subtitle: nil, runtime: 100, year: 2005, diskType: .bluRay),
    MediaItem(id: 166424, title: "Fantastic Four", subtitle: nil, runtime: 102, year: 2015, diskType: .dvd),
    MediaItem(id: 1979, title: "Fantastic Four", subtitle: "Rise of the Silver Surfer", runtime: 88, year: 2007, diskType: .dvd),
    MediaItem(id: 12, title: "Findet Nemo", subtitle: nil, runtime: 96, year: 2003, diskType: .dvd),
    MediaItem(id: 22, title: "Pirates of the Caribbean", subtitle: "The Curse of the Black Pearl", runtime: 137, year: 2003, diskType: .dvd),
    MediaItem(id: 58, title: "Pirates of the Caribbean", subtitle: "Dead Man's Chest", runtime: 145, year: 2006, diskType: .dvd),
    MediaItem(id: 285, title: "Pirates of the Caribbean", subtitle: "Am Ende der Welt", runtime: 162, year: 2007, diskType: .dvd),
    MediaItem(id: 1865, title: "Pirates of the Caribbean", subtitle: "Fremde Gezeiten", runtime: 131, year: 2011, diskType: .dvd),
    MediaItem(id: 10122, title: "Der Flug des Navigators", subtitle: nil, runtime: 86, year: 1986, diskType: .dvd),
    MediaItem(id: 72559, title: "G.I. Joe", subtitle: "Die Abrechnung", runtime: 123, year: 2013, diskType: .bluRay),
    MediaItem(id: 14869, title: "G.I. Joe", subtitle: "Geheimauftrag Cobra", runtime: 113, year: 2009, diskType: .bluRay),
    MediaItem(id: 2268, title: "Der goldene Kompass", subtitle: nil, runtime: 109, year: 2007, diskType: .dvd),
    MediaItem(id: 489, title: "Good Will Hunting", subtitle: nil, runtime: 120, year: 1997, diskType: .dvd),
    MediaItem(id: 49047, title: "Gravity", subtitle: nil, runtime: 91, year: 2013, diskType: .bluRay),
    MediaItem(id: 9836, title: "Happy Feet", subtitle: nil, runtime: 104, year: 2006, diskType: .dvd),
    MediaItem(id: 65759, title: "Happy Feet 2", subtitle: nil, runtime: 99, year: 2011, diskType: .bluRay),
    MediaItem(id: 671, title: "Harry Potter", subtitle: "Der Stein der Weisen", runtime: 147, year: 2001, diskType: .dvd),
    MediaItem(id: 672, title: "Harry Potter", subtitle: "Die Kammer des Schreckens", runtime: 153, year: 2002, diskType: .dvd),
    MediaItem(id: 673, title: "Harry Potter", subtitle: "Der Gefangene von Askaban", runtime: 136, year: 2004, diskType: .dvd),
    MediaItem(id: 674, title: "Harry Potter", subtitle: "Der Feuerkelch", runtime: 151, year: 2005, diskType: .dvd),
    MediaItem(id: 675, title: "Harry Potter", subtitle: "Der Orden des Phönix", runtime: 133, year: 2007, diskType: .dvd),
    MediaItem(id: 767, title: "Harry Potter", subtitle: "Der Halbblutprinz", runtime: 147, year: 2009, diskType: .dvd),
    MediaItem(id: 12444, title: "Harry Potter", subtitle: "Die Heiligtümer des Todes - Teil 1", runtime: 146, year: 2010, diskType: .bluRay),
    MediaItem(id: 12445, title: "Harry Potter", subtitle: "Die Heiligtümer des Todes - Teil 2", runtime: 130, year: 2011, diskType: .bluRay),
    MediaItem(id: 11385, title: "Hatari", subtitle: nil, runtime: 151, year: 1962, diskType: .dvd),
    MediaItem(id: 9520, title: "Herr der Diebe", subtitle: nil, runtime: 94, year: 2006, diskType: .dvd),
    MediaItem(id: 120, title: "Der Herr der Ringe", subtitle: "Die Gefährten", runtime: 171, year: 2001, diskType: .dvd),
    MediaItem(id: 121, title: "Der Herr der Ringe", subtitle: "Die zwei Türme", runtime: 172, year: 2002, diskType: .dvd),
    MediaItem(id: 122, title: "Der Herr der Ringe", subtitle: "Die Rückkehr des Königs", runtime: 192, year: 2003, diskType: .dvd),
    MediaItem(id: 9078, title: "Die Hexe und der Zauberer", subtitle: nil, runtime: 76, year: 1963, diskType: .dvd),
    MediaItem(id: 12222, title: "Horton hört ein Hu!", subtitle: nil, runtime: 83, year: 2008, diskType: .dvd),
    MediaItem(id: 11651, title: "Hui Buh", subtitle: "Das Schlossgespenst", runtime: 98, year: 2006, diskType: .dvd),
    MediaItem(id: 81188, title: "Die Hüter des Lichts", subtitle: nil, runtime: 97, year: 2012, diskType: .bluRay),
    MediaItem(id: 6479, title: "I Am Legend", subtitle: nil, runtime: 100, year: 2007, diskType: .bluRay),
    MediaItem(id: 425, title: "Ice Age", subtitle: nil, runtime: 78, year: 2002, diskType: .dvd),
    MediaItem(id: 950, title: "Ice Age 2", subtitle: "Jetzt taut's", runtime: 87, year: 2006, diskType: .dvd),
    MediaItem(id: 8355, title: "Ice Age 3", subtitle: "Die Dinosaurier sind los", runtime: 93, year: 2009, diskType: .bluRay),
    MediaItem(id: 57800, title: "Ice Age 4", subtitle: "Voll Verschoben", runtime: 88, year: 2012, diskType: .bluRay),
    MediaItem(id: 278154, title: "Ice Age 5", subtitle: "Kollision Voraus!", runtime: 94, year: 2016, diskType: .bluRay),
    MediaItem(id: 20352, title: "Ich - Einfach Unverbesserlich", subtitle: nil, runtime: 95, year: 2014, diskType: .bluRay),
    MediaItem(id: 93456, title: "Ich - Einfach Unverbesserlich 2", subtitle: nil, runtime: 98, year: 2013, diskType: .bluRay),
    MediaItem(id: 46529, title: "Ich bin Nummer Vier", subtitle: nil, runtime: 105, year: 2011, diskType: .dvd),
    MediaItem(id: 27205, title: "Inception", subtitle: nil, runtime: 148, year: 2010, diskType: .bluRay),
    MediaItem(id: 602, title: "Independence Day", subtitle: nil, runtime: 154, year: 1996, diskType: .bluRay),
    MediaItem(id: 47933, title: "Independence Day", subtitle: "Wiederkehr", runtime: 120, year: 2016, diskType: .bluRay),
    MediaItem(id: 85, title: "Indiana Jones", subtitle: "Jäger des verlorenen Schatzes", runtime: 111, year: 1981, diskType: .dvd),
    MediaItem(id: 217, title: "Indiana Jones", subtitle: "Das Königreich des Kristallschädels", runtime: 117, year: 2008, diskType: .dvd),
    MediaItem(id: 87, title: "Indiana Jones", subtitle: "Der Tempel des Todes", runtime: 114, year: 1984, diskType: .dvd),
    MediaItem(id: 89, title: "Indiana Jones", subtitle: "Der letzte Kreuzzug", runtime: 122, year: 1989, diskType: .dvd),
    MediaItem(id: 157336, title: "Interstellar", subtitle: nil, runtime: 169, year: 2014, diskType: .bluRay),
    MediaItem(id: 1726, title: "Iron Man", subtitle: nil, runtime: 126, year: 2008, diskType: .bluRay),
    MediaItem(id: 10138, title: "Iron Man 2", subtitle: nil, runtime: 126, year: 2010, diskType: .bluRay),
    MediaItem(id: 68721, title: "Iron Man 3", subtitle: nil, runtime: 131, year: 2013, diskType: .bluRay),
    MediaItem(id: 36669, title: "James Bond 007", subtitle: "Stirb an einem anderen Tag", runtime: 127, year: 2002, diskType: .dvd),
    MediaItem(id: 9486, title: "Johnny English", subtitle: "Der Spion, der es versiebte", runtime: 84, year: 2003, diskType: .dvd),
    MediaItem(id: 9482, title: "Judge Dredd", subtitle: nil, runtime: 93, year: 1995, diskType: .dvd),
    MediaItem(id: 135397, title: "Jurassic World", subtitle: nil, runtime: 124, year: 2015, diskType: .bluRay),
    MediaItem(id: 4627, title: "Krabat", subtitle: nil, runtime: 115, year: 2008, diskType: .dvd),
    MediaItem(id: 9502, title: "Kung Fu Panda", subtitle: nil, runtime: 88, year: 2008, diskType: .dvd),
    MediaItem(id: 49444, title: "Kung Fu Panda 2", subtitle: nil, runtime: 87, year: 2011, diskType: .dvd),
    MediaItem(id: 140300, title: "Kung Fu Panda 3", subtitle: nil, runtime: 95, year: 2016, diskType: .bluRay),
    MediaItem(id: 8587, title: "Der König der Löwen", subtitle: nil, runtime: 85, year: 1994, diskType: .dvd),
    MediaItem(id: 10198, title: "Küss den Frosch", subtitle: nil, runtime: 98, year: 2009, diskType: .bluRay),
    MediaItem(id: 267860, title: "London Has Fallen", subtitle: nil, runtime: 99, year: 2016, diskType: .bluRay),
    MediaItem(id: 953, title: "Madagascar", subtitle: nil, runtime: 86, year: 2005, diskType: .bluRay),
    MediaItem(id: 10527, title: "Madagascar 2", subtitle: nil, runtime: 89, year: 2008, diskType: .bluRay),
    MediaItem(id: 80321, title: "Madagascar 3", subtitle: "Flucht durch Europa", runtime: 90, year: 2012, diskType: .bluRay),
    MediaItem(id: 102651, title: "Maleficent", subtitle: "Die dunkle Fee", runtime: 97, year: 2014, diskType: .bluRay),
    MediaItem(id: 198663, title: "Maze Runner", subtitle: "Die Auserwählten im Labyrinth", runtime: 113, year: 2014, diskType: .bluRay),
    MediaItem(id: 294254, title: "Maze Runner", subtitle: "Die Auserwählten in der Brandwüste", runtime: 132, year: 2015, diskType: .bluRay),
    MediaItem(id: 38055, title: "Megamind", subtitle: nil, runtime: 95, year: 2010, diskType: .bluRay),
    MediaItem(id: 62177, title: "Merida", subtitle: "Legende der Highlands", runtime: 93, year: 2012, diskType: .bluRay),
    MediaItem(id: 211672, title: "Minions", subtitle: nil, runtime: 91, year: 2015, diskType: .bluRay),
    MediaItem(id: 45342, title: "Miss Marple", subtitle: "16 Uhr 50 ab Paddington", runtime: 82, year: 1987, diskType: .dvd),
    MediaItem(id: 758, title: "Miss Marple 2", subtitle: "Mörder Ahoi", runtime: 89, year: 1964, diskType: .dvd),
    MediaItem(id: 751, title: "Miss Marple 3", subtitle: "Der Wachsblumenstrauß", runtime: 78, year: 1963, diskType: .dvd),
    MediaItem(id: 757, title: "Miss Marple 4", subtitle: "Vier Frauen und ein Mord", runtime: 87, year: 1987, diskType: .dvd),
    MediaItem(id: 15512, title: "Monsters vs Aliens", subtitle: nil, runtime: 90, year: 2009, diskType: .dvd),
    MediaItem(id: 10674, title: "Mulan", subtitle: nil, runtime: 88, year: 1998, diskType: .bluRay),
    MediaItem(id: 1593, title: "Nachts im Museum", subtitle: nil, runtime: 104, year: 2006, diskType: .dvd),
    MediaItem(id: 18360, title: "Nachts im Museum 2", subtitle: nil, runtime: 100, year: 2009, diskType: .dvd),
    MediaItem(id: 411, title: "Die Chroniken von Narnia", subtitle: "Der König von Narnia", runtime: 136, year: 2005, diskType: .dvd),
    MediaItem(id: 10140, title: "Die Chroniken von Narnia", subtitle: "Die Reise Auf der Morgenröte", runtime: 107, year: 2010, diskType: .dvd),
    MediaItem(id: 2454, title: "Die Chroniken von Narnia", subtitle: "Prinz Kaspian von Narnia", runtime: 144, year: 2008, diskType: .dvd),
    MediaItem(id: 18239, title: "The Twilight Saga", subtitle: "New Moon", runtime: 125, year: 2009, diskType: .dvd),
    MediaItem(id: 14160, title: "Oben", subtitle: nil, runtime: 96, year: 2009, diskType: .bluRay),
    MediaItem(id: 117263, title: "Olympus Has Fallen", subtitle: "Die Welt in Gefahr", runtime: 119, year: 2013, diskType: .bluRay),
    MediaItem(id: 227783, title: "Operation Nussknacker", subtitle: nil, runtime: 85, year: 2014, diskType: .bluRay),
    MediaItem(id: 23827, title: "Paranormal Activity", subtitle: nil, runtime: 86, year: 2007, diskType: .bluRay),
    MediaItem(id: 41436, title: "Paranormal Activity 2", subtitle: nil, runtime: 98, year: 2010, diskType: .bluRay),
    MediaItem(id: 72571, title: "Paranormal Activity 3", subtitle: nil, runtime: 94, year: 2011, diskType: .bluRay),
    MediaItem(id: 82990, title: "Paranormal Activity 4", subtitle: nil, runtime: 97, year: 2012, diskType: .bluRay),
    MediaItem(id: 32657, title: "Percy Jackson", subtitle: "Diebe im Olymp", runtime: 119, year: 2010, diskType: .bluRay),
    MediaItem(id: 76285, title: "Percy Jackson", subtitle: "Im Bann des Zyklopen", runtime: 106, year: 2013, diskType: .bluRay),
    MediaItem(id: 328111, title: "Pets", subtitle: nil, runtime: 86, year: 2016, diskType: .bluRay),
    MediaItem(id: 71689, title: "Phineas und Ferb", subtitle: "Quer durch die 2. Dimension", runtime: 74, year: 2011, diskType: .dvd),
    MediaItem(id: 61791, title: "Planet der Affen", subtitle: "Prevolution", runtime: 105, year: 2011, diskType: .bluRay),
    MediaItem(id: 119450, title: "Planet der Affen", subtitle: "Revolution", runtime: 130, year: 2014, diskType: .bluRay),
    MediaItem(id: 10530, title: "Pocahontas", subtitle: nil, runtime: 81, year: 1995, diskType: .bluRay),
    MediaItem(id: 114, title: "Pretty Woman", subtitle: nil, runtime: 115, year: 1990, diskType: .dvd),
    MediaItem(id: 9543, title: "Prince of Persia", subtitle: "Der Sand der Zeit", runtime: 116, year: 2010, diskType: .bluRay),
    MediaItem(id: 38757, title: "Rapunzel", subtitle: "Neu verföhnt", runtime: 100, year: 2010, diskType: .bluRay),
    MediaItem(id: 2062, title: "Ratatouille", subtitle: nil, runtime: 108, year: 2007, diskType: .dvd),
    MediaItem(id: 46195, title: "Rio", subtitle: nil, runtime: 92, year: 2011, diskType: .dvd),
    MediaItem(id: 172385, title: "Rio 2", subtitle: "Dschungelfieber", runtime: 101, year: 2014, diskType: .bluRay),
    MediaItem(id: 11886, title: "Robin Hood", subtitle: nil, runtime: 80, year: 1973, diskType: .bluRay),
    MediaItem(id: 8367, title: "Robin Hood", subtitle: "König der Diebe", runtime: 137, year: 1991, diskType: .dvd),
    MediaItem(id: 9928, title: "Robots", subtitle: nil, runtime: 90, year: 2005, diskType: .bluRay),
    MediaItem(id: 10528, title: "Sherlock Holmes", subtitle: nil, runtime: 129, year: 2009, diskType: .bluRay),
    MediaItem(id: 58574, title: "Sherlock Holmes", subtitle: "Spiel im Schatten", runtime: 129, year: 2011, diskType: .bluRay),
    MediaItem(id: 58595, title: "Snow White and the Huntsman", subtitle: nil, runtime: 131, year: 2012, diskType: .bluRay),
    MediaItem(id: 10054, title: "Spy Kids", subtitle: nil, runtime: 88, year: 2001, diskType: .dvd),
    MediaItem(id: 9488, title: "Spy Kids 2", subtitle: "Die Rückkehr der Superspione", runtime: 96, year: 2002, diskType: .dvd),
    MediaItem(id: 13475, title: "Star Trek", subtitle: nil, runtime: 122, year: 2009, diskType: .dvd),
    MediaItem(id: 188927, title: "Star Trek", subtitle: "Beyond", runtime: 122, year: 2016, diskType: .bluRay),
    MediaItem(id: 54138, title: "Star Trek", subtitle: "Into Darkness", runtime: 127, year: 2013, diskType: .dvd),
    MediaItem(id: 1894, title: "Star Wars II", subtitle: "Angriff der Klonkrieger", runtime: 137, year: 2002, diskType: .dvd),
    MediaItem(id: 140607, title: "Star Wars VII", subtitle: "Das Erwachen der Macht", runtime: 135, year: 2015, diskType: .bluRay),
    MediaItem(id: 1891, title: "Star Wars V", subtitle: "Das Imperium schlägt zurück", runtime: 124, year: 1980, diskType: .dvd),
    MediaItem(id: 1895, title: "Star Wars III", subtitle: "Die Rache der Sith", runtime: 134, year: 2005, diskType: .dvd),
    MediaItem(id: 1892, title: "Star Wars VI", subtitle: "Die Rückkehr der Jedi-Ritter", runtime: 131, year: 1983, diskType: .dvd),
    MediaItem(id: 1893, title: "Star Wars I", subtitle: "Die dunkle Bedrohung", runtime: 130, year: 1999, diskType: .dvd),
    MediaItem(id: 11, title: "Star Wars IV", subtitle: "Eine neue Hoffnung", runtime: 120, year: 1977, diskType: .dvd),
    MediaItem(id: 2756, title: "The Abyss", subtitle: "Abgrund des Todes", runtime: 167, year: 1989, diskType: .dvd),
    MediaItem(id: 1930, title: "The Amazing Spider-Man", subtitle: nil, runtime: 136, year: 2012, diskType: .bluRay),
    MediaItem(id: 102382, title: "The Amazing Spider-Man 2", subtitle: "Rise of Electro", runtime: 141, year: 2014, diskType: .bluRay),
    MediaItem(id: 24428, title: "The Avengers", subtitle: nil, runtime: 143, year: 2012, diskType: .bluRay),
    MediaItem(id: 99861, title: "The Avengers 2", subtitle: "Age of Ultron", runtime: 141, year: 2015, diskType: .bluRay),
    MediaItem(id: 155, title: "The Dark Knight", subtitle: nil, runtime: 152, year: 2008, diskType: .bluRay),
    MediaItem(id: 49026, title: "The Dark Knight Rises", subtitle: nil, runtime: 165, year: 2012, diskType: .bluRay),
    MediaItem(id: 435, title: "The Day After Tomorrow", subtitle: nil, runtime: 119, year: 2004, diskType: .dvd),
    MediaItem(id: 70160, title: "The Hunger Games", subtitle: nil, runtime: 142, year: 2012, diskType: .bluRay),
    MediaItem(id: 101299, title: "The Hunger Games", subtitle: "Catching Fire", runtime: 146, year: 2013, diskType: .bluRay),
    MediaItem(id: 131631, title: "The Hunger Games", subtitle: "Mockingjay - Teil 1", runtime: 123, year: 2014, diskType: .bluRay),
    MediaItem(id: 131634, title: "The Hunger Games", subtitle: "Mockingjay - Teil 2", runtime: 138, year: 2015, diskType: .bluRay),
    MediaItem(id: 290595, title: "The Huntsman & the Ice Queen", subtitle: nil, runtime: 114, year: 2016, diskType: .bluRay),
    MediaItem(id: 278927, title: "The Jungle Book", subtitle: nil, runtime: 106, year: 2016, diskType: .bluRay),
    MediaItem(id: 258489, title: "Legend Of Tarzan", subtitle: nil, runtime: 110, year: 2016, diskType: .bluRay),
    MediaItem(id: 10195, title: "Thor", subtitle: nil, runtime: 115, year: 2011, diskType: .bluRay),
    MediaItem(id: 76338, title: "Thor", subtitle: "The Dark Kingdom", runtime: 112, year: 2013, diskType: .bluRay),
    MediaItem(id: 597, title: "Titanic", subtitle: nil, runtime: 194, year: 1997, diskType: .bluRay),
    MediaItem(id: 10193, title: "Toy Story 3", subtitle: nil, runtime: 102, year: 2010, diskType: .bluRay),
    MediaItem(id: 1858, title: "Transformers", subtitle: nil, runtime: 138, year: 2007, diskType: .dvd),
    MediaItem(id: 8373, title: "Transformers 2", subtitle: "Die Rache", runtime: 144, year: 2009, diskType: .dvd),
    MediaItem(id: 38356, title: "Transformers 3", subtitle: "Die dunkle Seite des Mondes", runtime: 148, year: 2011, diskType: .dvd),
    MediaItem(id: 91314, title: "Transformers 4", subtitle: "Ära des Untergangs", runtime: 165, year: 2014, diskType: .bluRay),
    MediaItem(id: 97, title: "Tron", subtitle: nil, runtime: 125, year: 1982, diskType: .bluRay),
    MediaItem(id: 77950, title: "Turbo", subtitle: "Kleine Schnecke, großer Traum", runtime: 96, year: 2013, diskType: .bluRay),
    MediaItem(id: 8966, title: "Twilight", subtitle: nil, runtime: 117, year: 2008, diskType: .dvd),
    MediaItem(id: 10681, title: "Wall-E", subtitle: "Der Letzte räumt die Erde auf", runtime: 95, year: 2008, diskType: .dvd),
    MediaItem(id: 117251, title: "White House Down", subtitle: nil, runtime: 131, year: 2013, diskType: .bluRay),
    MediaItem(id: 22794, title: "Wolkig mit Aussicht auf Fleischbällchen", subtitle: nil, runtime: 90, year: 2009, diskType: .bluRay),
    MediaItem(id: 109451, title: "Wolkig mit Aussicht auf Fleischbällchen 2", subtitle: nil, runtime: 95, year: 2013, diskType: .bluRay),
    MediaItem(id: 72190, title: "World War Z", subtitle: nil, runtime: 123, year: 2013, diskType: .bluRay),
    MediaItem(id: 246655, title: "X-Men", subtitle: "Apocalypse", runtime: 104, year: 2016, diskType: .bluRay),
    MediaItem(id: 36668, title: "X-Men", subtitle: "Der letzte Widerstand", runtime: 104, year: 2006, diskType: .bluRay),
    MediaItem(id: 36658, title: "X-Men 2", subtitle: nil, runtime: 134, year: 2003, diskType: .bluRay),
    MediaItem(id: 2080, title: "X-Men Origins", subtitle: "Wolverine", runtime: 107, year: 2009, diskType: .bluRay),
    MediaItem(id: 49538, title: "X-Men", subtitle: "Erste Entscheidung", runtime: 132, year: 2011, diskType: .bluRay),
    MediaItem(id: 127585, title: "X-Men", subtitle: "Zukunft ist Vergangenheit", runtime: 132, year: 2014, diskType: .bluRay),
    MediaItem(id: 269149, title: "Zoomania", subtitle: nil, runtime: 108, year: 2016, diskType: .bluRay)
  ]
  // swiftlint:enable line_length

  func add(_ mediaItem: MediaItem) throws {
    throw MediaLibraryError.storageError
  }

  func replaceItems(_ mediaItems: [MediaItem]) throws {
    throw MediaLibraryError.storageError
  }

  func mediaItems(where predicate: (MediaItem) -> Bool) -> [MediaItem] {
    return data.filter(predicate)
  }

}
